- name: Install pip module
  apt:
    name: python3-pip
    state: present

- name: Creates directory
  file:
    path: /app
    state: directory

- name: Git clone
  git:
    repo: 'https://github.com/anfederico/Flaskex'
    dest: /app

- name: Install specified python requirements
  pip:
    requirements: /app/requirements.txt

- name: run app
  shell: 'nohup python3 /app/app.py &'
  
- name: Wait for port 5000 to become open on the host, don't start checking for 10 seconds
  wait_for:
   port: 5000
   delay: 2
   timeout: 15